"""Seed catalogue for the Gyffty storefront.

Five pillars, each with curated collections beneath it, and a hamper catalogue
rich enough to exercise every filter, badge and rail in the UI.

Images point at picsum.photos with stable seeds so the storefront renders out of
the box. Swap `image_seed` for your real CDN paths before launch.
"""

from __future__ import annotations

CATEGORIES: list[dict] = [
    {
        "slug": "customised",
        "name": "Customised",
        "tagline": "Made for one person only",
        "description": (
            "Engraved keepsakes, hand-picked contents and a hamper built around the "
            "person you are sending it to. Choose the box, choose what goes in it, "
            "add their name."
        ),
        "accent_color": "#B08D57",
        "icon": "sparkles",
        "display_order": 1,
        "is_featured": True,
        "children": [
            {"slug": "build-your-own-hamper", "name": "Build Your Own Hamper"},
            {"slug": "engraved-keepsakes", "name": "Engraved Keepsakes"},
            {"slug": "photo-personalised", "name": "Photo Personalised"},
            {"slug": "custom-corporate", "name": "Corporate & Bulk"},
        ],
    },
    {
        "slug": "relationship",
        "name": "Relationship",
        "tagline": "For the people who matter",
        "description": (
            "Curated by who is receiving it, not what the calendar says. For her, "
            "for him, for parents, for the friend who always shows up."
        ),
        "accent_color": "#C2185B",
        "icon": "heart",
        "display_order": 2,
        "is_featured": True,
        "children": [
            {"slug": "for-her", "name": "For Her"},
            {"slug": "for-him", "name": "For Him"},
            {"slug": "for-parents", "name": "For Parents"},
            {"slug": "for-friends", "name": "For Friends"},
            {"slug": "for-couples", "name": "For Couples"},
        ],
    },
    {
        "slug": "festival",
        "name": "Festival",
        "tagline": "Every celebration, beautifully boxed",
        "description": (
            "Diwali, Raksha Bandhan, Christmas, Holi and Eid hampers assembled by "
            "our studio, ready to send across India."
        ),
        "accent_color": "#E07A2F",
        "icon": "lantern",
        "display_order": 3,
        "is_featured": True,
        "children": [
            {"slug": "diwali", "name": "Diwali"},
            {"slug": "raksha-bandhan", "name": "Raksha Bandhan"},
            {"slug": "christmas", "name": "Christmas"},
            {"slug": "holi", "name": "Holi"},
            {"slug": "eid", "name": "Eid"},
        ],
    },
    {
        "slug": "anniversary",
        "name": "Anniversary",
        "tagline": "One more year, marked properly",
        "description": (
            "Milestone hampers for first anniversaries through silver and gold, "
            "plus wedding and work anniversaries."
        ),
        "accent_color": "#7B2D5B",
        "icon": "rings",
        "display_order": 4,
        "is_featured": True,
        "children": [
            {"slug": "first-anniversary", "name": "First Anniversary"},
            {"slug": "milestone-years", "name": "Milestone Years"},
            {"slug": "wedding-gifting", "name": "Wedding Gifting"},
            {"slug": "work-anniversary", "name": "Work Anniversary"},
        ],
    },
    {
        "slug": "birthday",
        "name": "Birthday",
        "tagline": "Arrive before the cake does",
        "description": (
            "Birthday hampers with same-day delivery across metros, from midnight "
            "surprises to milestone boxes."
        ),
        "accent_color": "#1E7A6F",
        "icon": "cake",
        "display_order": 5,
        "is_featured": True,
        "children": [
            {"slug": "midnight-surprise", "name": "Midnight Surprise"},
            {"slug": "milestone-birthdays", "name": "Milestone Birthdays"},
            {"slug": "for-kids", "name": "For Kids"},
            {"slug": "birthday-luxe", "name": "Birthday LUXE"},
        ],
    },
]


def _p(**kwargs) -> dict:
    """Product record with sensible defaults so each entry below stays readable."""
    base = {
        "compare_at_price": None,
        "occasion_tags": "",
        "recipient_tags": "",
        "theme_tags": "",
        "is_customisable": False,
        "allows_message_card": True,
        "allows_engraving": False,
        "stock_quantity": 40,
        "is_bestseller": False,
        "is_new_arrival": False,
        "is_luxe": False,
        "same_day_delivery": False,
        "rating_average": 4.5,
        "rating_count": 24,
        "sold_count": 60,
        "inclusions": [],
    }
    base.update(kwargs)
    return base


PRODUCTS: list[dict] = [
    # ---------------- Customised ----------------
    _p(
        category="build-your-own-hamper",
        name="Signature Build-Your-Own Hamper Box",
        short_description="Pick the box, pick the contents, we assemble and ship it the same week.",
        description=(
            "Start with our signature rigid keepsake box in matte ivory, then choose up "
            "to eight items from the studio pantry. Each hamper is packed by hand with "
            "shredded silk filler, a wax-sealed note and a ribbon in the colour you pick."
        ),
        price=2499,
        compare_at_price=2999,
        occasion_tags="birthday,anniversary,thank-you,congratulations",
        recipient_tags="for-her,for-him,for-parents,for-friends",
        theme_tags="gourmet,keepsake,build-your-own",
        is_customisable=True,
        allows_engraving=True,
        same_day_delivery=False,
        is_bestseller=True,
        rating_average=4.8,
        rating_count=312,
        sold_count=1240,
        inclusions=[
            {"name": "Signature rigid keepsake box", "quantity": "1"},
            {"name": "Choice of 8 pantry items", "quantity": "8"},
            {"name": "Wax-sealed handwritten note", "quantity": "1"},
            {"name": "Satin ribbon in your chosen colour", "quantity": "1"},
        ],
    ),
    _p(
        category="engraved-keepsakes",
        name="Monogram Walnut Keepsake Chest",
        short_description="Solid walnut chest, laser-engraved with up to three initials.",
        description=(
            "A heirloom-grade walnut chest with brass hinges, engraved on the lid with "
            "the monogram of your choice. Lined in charcoal felt and large enough to "
            "hold letters, watches or a small bottle."
        ),
        price=5899,
        compare_at_price=6999,
        occasion_tags="anniversary,wedding,retirement,housewarming",
        recipient_tags="for-him,for-parents,for-couples",
        theme_tags="keepsake,wood,engraved,luxe",
        is_customisable=True,
        allows_engraving=True,
        is_luxe=True,
        rating_average=4.9,
        rating_count=148,
        sold_count=420,
        stock_quantity=18,
        inclusions=[
            {"name": "Walnut chest with brass hinges", "quantity": "1"},
            {"name": "Laser engraving, up to 3 initials", "quantity": "1"},
            {"name": "Charcoal felt lining", "quantity": "1"},
        ],
    ),
    _p(
        category="photo-personalised",
        name="Memory Lane Photo Hamper",
        short_description="Twelve of your photographs, printed and boxed with their favourites.",
        description=(
            "Upload twelve photographs and we print them on archival matte stock, bind "
            "them into a linen album and pack the album with artisan chocolate, a soy "
            "candle and a hand-lettered card."
        ),
        price=3299,
        occasion_tags="birthday,anniversary,friendship-day",
        recipient_tags="for-her,for-friends,for-couples",
        theme_tags="photo,keepsake,chocolate,candle",
        is_customisable=True,
        is_new_arrival=True,
        rating_average=4.7,
        rating_count=96,
        sold_count=310,
        inclusions=[
            {"name": "Linen photo album, 12 archival prints", "quantity": "1"},
            {"name": "Artisan dark chocolate bar", "quantity": "2"},
            {"name": "Soy wax candle, sandalwood", "quantity": "1"},
            {"name": "Hand-lettered card", "quantity": "1"},
        ],
    ),
    _p(
        category="custom-corporate",
        name="Onboarding Welcome Kit, Branded",
        short_description="New-hire kit with your logo on every piece. Minimum order 25.",
        description=(
            "A first-day kit that does not look like swag. Canvas laptop sleeve, brass "
            "pen, ceramic mug, notebook and single-origin coffee, each carrying your "
            "brand mark, packed in a branded rigid box."
        ),
        price=3899,
        compare_at_price=4499,
        occasion_tags="onboarding,corporate,congratulations",
        recipient_tags="corporate,for-him,for-her",
        theme_tags="corporate,branded,stationery,coffee",
        is_customisable=True,
        allows_engraving=True,
        stock_quantity=200,
        sold_count=2400,
        is_bestseller=True,
        rating_average=4.6,
        rating_count=88,
        inclusions=[
            {"name": "Canvas laptop sleeve, branded", "quantity": "1"},
            {"name": "Brass rollerball pen, engraved", "quantity": "1"},
            {"name": "Ceramic mug, branded", "quantity": "1"},
            {"name": "A5 hardbound notebook", "quantity": "1"},
            {"name": "Single-origin coffee", "quantity": "250g"},
        ],
    ),
    _p(
        category="build-your-own-hamper",
        name="Petite Custom Hamper",
        short_description="A smaller build-your-own box, four items, under two thousand.",
        price=1499,
        compare_at_price=1799,
        occasion_tags="thank-you,birthday,get-well",
        recipient_tags="for-friends,for-her,for-him",
        theme_tags="build-your-own,gourmet,compact",
        is_customisable=True,
        same_day_delivery=True,
        is_new_arrival=True,
        rating_average=4.5,
        rating_count=64,
        sold_count=280,
        inclusions=[
            {"name": "Petite kraft hamper box", "quantity": "1"},
            {"name": "Choice of 4 pantry items", "quantity": "4"},
            {"name": "Message card", "quantity": "1"},
        ],
    ),
    # ---------------- Relationship ----------------
    _p(
        category="for-her",
        name="Rose Atelier Pamper Hamper",
        short_description="Rose-led bath ritual, Darjeeling first flush and a silk eye mask.",
        description=(
            "Everything needed for an evening that belongs entirely to her. Rose bath "
            "salts, a cold-pressed body oil, first-flush Darjeeling, a mulberry silk eye "
            "mask and single-origin chocolate, in a blush rigid box."
        ),
        price=3499,
        compare_at_price=4199,
        occasion_tags="birthday,anniversary,valentines,womens-day",
        recipient_tags="for-her,for-couples",
        theme_tags="spa,tea,chocolate,rose,self-care",
        is_bestseller=True,
        same_day_delivery=True,
        rating_average=4.8,
        rating_count=421,
        sold_count=1580,
        inclusions=[
            {"name": "Himalayan rose bath salts", "quantity": "300g"},
            {"name": "Cold-pressed body oil", "quantity": "100ml"},
            {"name": "Darjeeling first flush tea", "quantity": "50g"},
            {"name": "Mulberry silk eye mask", "quantity": "1"},
            {"name": "Single-origin chocolate", "quantity": "2 bars"},
        ],
    ),
    _p(
        category="for-him",
        name="The Gentlemans Reserve",
        short_description="Whisky stones, leather coasters and smoked almonds in an oak crate.",
        description=(
            "A crate built around the hour after work. Granite whisky stones in a velvet "
            "pouch, full-grain leather coasters, smoked almonds, dark chocolate with sea "
            "salt and a cedar-and-vetiver candle."
        ),
        price=4299,
        compare_at_price=4999,
        occasion_tags="birthday,anniversary,fathers-day,promotion",
        recipient_tags="for-him,for-parents",
        theme_tags="barware,leather,gourmet,masculine",
        is_bestseller=True,
        allows_engraving=True,
        rating_average=4.7,
        rating_count=286,
        sold_count=980,
        inclusions=[
            {"name": "Granite whisky stones, set of 9", "quantity": "1 set"},
            {"name": "Full-grain leather coasters", "quantity": "4"},
            {"name": "Smoked almonds", "quantity": "200g"},
            {"name": "Sea-salt dark chocolate", "quantity": "2 bars"},
            {"name": "Cedar and vetiver candle", "quantity": "1"},
        ],
    ),
    _p(
        category="for-parents",
        name="Sunday Morning Hamper",
        short_description="Filter coffee, jaggery cookies and a marbled ceramic pair.",
        price=2799,
        occasion_tags="anniversary,mothers-day,fathers-day,thank-you",
        recipient_tags="for-parents,for-couples",
        theme_tags="coffee,ceramic,bakery,comfort",
        same_day_delivery=True,
        rating_average=4.6,
        rating_count=193,
        sold_count=640,
        inclusions=[
            {"name": "South Indian filter coffee blend", "quantity": "250g"},
            {"name": "Stainless steel filter set", "quantity": "1"},
            {"name": "Marbled ceramic mugs", "quantity": "2"},
            {"name": "Jaggery and cashew cookies", "quantity": "300g"},
        ],
    ),
    _p(
        category="for-friends",
        name="Movie Night In A Box",
        short_description="Truffle popcorn, soda syrups and a card game, for the group chat.",
        price=1899,
        compare_at_price=2299,
        occasion_tags="friendship-day,birthday,get-together,housewarming",
        recipient_tags="for-friends,for-her,for-him",
        theme_tags="snacks,games,movie-night,fun",
        same_day_delivery=True,
        is_new_arrival=True,
        rating_average=4.5,
        rating_count=157,
        sold_count=720,
        inclusions=[
            {"name": "Truffle and cheddar popcorn", "quantity": "2 packs"},
            {"name": "Artisanal soda syrups", "quantity": "2 x 200ml"},
            {"name": "Party card game", "quantity": "1"},
            {"name": "Salted caramel brittle", "quantity": "150g"},
        ],
    ),
    _p(
        category="for-couples",
        name="Date Night Ritual Hamper",
        short_description="Two candles, a dessert kit and a deck of conversation cards.",
        price=3199,
        occasion_tags="anniversary,valentines,date-night",
        recipient_tags="for-couples,for-her,for-him",
        theme_tags="romance,dessert,candle,intimate",
        is_bestseller=True,
        rating_average=4.8,
        rating_count=238,
        sold_count=860,
        inclusions=[
            {"name": "Taper candles with brass holders", "quantity": "2"},
            {"name": "Chocolate fondue dessert kit", "quantity": "1"},
            {"name": "Conversation card deck", "quantity": "1"},
            {"name": "Sparkling grape pressing", "quantity": "750ml"},
        ],
    ),
    _p(
        category="for-her",
        name="Bloom and Bar Hamper",
        short_description="Preserved roses that last a year, with couverture chocolate.",
        price=4799,
        compare_at_price=5599,
        occasion_tags="anniversary,valentines,birthday",
        recipient_tags="for-her,for-couples",
        theme_tags="flowers,chocolate,luxe,preserved",
        is_luxe=True,
        same_day_delivery=True,
        rating_average=4.9,
        rating_count=204,
        sold_count=560,
        stock_quantity=22,
        inclusions=[
            {"name": "Preserved roses in a hatbox", "quantity": "12 stems"},
            {"name": "Couverture chocolate assortment", "quantity": "18 pieces"},
            {"name": "Handwritten note on cotton stock", "quantity": "1"},
        ],
    ),
    # ---------------- Festival ----------------
    _p(
        category="diwali",
        name="Deepavali Heritage Thali Hamper",
        short_description="Brass thali, hand-rolled diyas and kaju katli from a Jaipur halwai.",
        description=(
            "A festive hamper built around a hand-spun brass thali. Includes six "
            "terracotta diyas painted by artisans in Khurja, kaju katli, dry fruits and "
            "a pair of silver-plated Lakshmi-Ganesh idols."
        ),
        price=4499,
        compare_at_price=5299,
        occasion_tags="diwali,festival,corporate",
        recipient_tags="for-parents,for-her,for-him,corporate",
        theme_tags="brass,sweets,dry-fruits,traditional",
        is_bestseller=True,
        rating_average=4.8,
        rating_count=368,
        sold_count=1920,
        inclusions=[
            {"name": "Hand-spun brass thali", "quantity": "1"},
            {"name": "Hand-painted terracotta diyas", "quantity": "6"},
            {"name": "Kaju katli", "quantity": "500g"},
            {"name": "Premium dry fruit mix", "quantity": "400g"},
            {"name": "Silver-plated idols", "quantity": "1 pair"},
        ],
    ),
    _p(
        category="diwali",
        name="Roshni Corporate Diwali Box",
        short_description="Logo-ready Diwali hamper for teams. Minimum order 50.",
        price=2299,
        compare_at_price=2699,
        occasion_tags="diwali,festival,corporate,onboarding",
        recipient_tags="corporate",
        theme_tags="corporate,branded,sweets,diyas",
        is_customisable=True,
        stock_quantity=500,
        sold_count=4100,
        rating_average=4.5,
        rating_count=112,
        inclusions=[
            {"name": "Branded rigid box", "quantity": "1"},
            {"name": "Assorted mithai", "quantity": "400g"},
            {"name": "Scented tealights", "quantity": "4"},
            {"name": "Roasted and salted dry fruits", "quantity": "250g"},
        ],
    ),
    _p(
        category="raksha-bandhan",
        name="Bandhan Rakhi and Sweets Hamper",
        short_description="Two handcrafted rakhis, motichoor laddoo and a roli-chawal set.",
        price=1799,
        compare_at_price=2199,
        occasion_tags="raksha-bandhan,festival",
        recipient_tags="for-him,for-friends",
        theme_tags="rakhi,sweets,traditional",
        same_day_delivery=True,
        is_bestseller=True,
        rating_average=4.7,
        rating_count=512,
        sold_count=3200,
        inclusions=[
            {"name": "Handcrafted thread rakhis", "quantity": "2"},
            {"name": "Motichoor laddoo", "quantity": "400g"},
            {"name": "Roli, chawal and mishri set", "quantity": "1"},
            {"name": "Greeting card", "quantity": "1"},
        ],
    ),
    _p(
        category="christmas",
        name="Winter Spice Christmas Crate",
        short_description="Mulled wine spices, stollen, gingerbread and a fir candle.",
        price=3599,
        compare_at_price=4199,
        occasion_tags="christmas,festival,new-year",
        recipient_tags="for-friends,for-parents,for-couples",
        theme_tags="bakery,spice,candle,winter",
        is_new_arrival=True,
        rating_average=4.6,
        rating_count=134,
        sold_count=480,
        inclusions=[
            {"name": "Mulled wine spice sachets", "quantity": "4"},
            {"name": "Almond stollen", "quantity": "450g"},
            {"name": "Iced gingerbread", "quantity": "12 pieces"},
            {"name": "Balsam fir candle", "quantity": "1"},
        ],
    ),
    _p(
        category="holi",
        name="Rang Utsav Holi Hamper",
        short_description="Herbal gulal, thandai concentrate and gujiya, in a painted trunk.",
        price=2199,
        occasion_tags="holi,festival",
        recipient_tags="for-friends,for-parents",
        theme_tags="gulal,sweets,thandai,colourful",
        same_day_delivery=True,
        rating_average=4.5,
        rating_count=98,
        sold_count=520,
        inclusions=[
            {"name": "Herbal gulal, 5 shades", "quantity": "5 x 100g"},
            {"name": "Thandai concentrate", "quantity": "500ml"},
            {"name": "Mawa gujiya", "quantity": "400g"},
            {"name": "Hand-painted tin trunk", "quantity": "1"},
        ],
    ),
    _p(
        category="eid",
        name="Eid Mubarak Dates and Dessert Box",
        short_description="Ajwa dates, baklava and kahwa in an embossed keepsake box.",
        price=3299,
        compare_at_price=3899,
        occasion_tags="eid,festival,ramadan",
        recipient_tags="for-parents,for-friends,corporate",
        theme_tags="dates,dessert,kahwa,traditional",
        rating_average=4.7,
        rating_count=176,
        sold_count=690,
        inclusions=[
            {"name": "Ajwa dates", "quantity": "500g"},
            {"name": "Pistachio baklava", "quantity": "400g"},
            {"name": "Kashmiri kahwa blend", "quantity": "100g"},
            {"name": "Embossed keepsake box", "quantity": "1"},
        ],
    ),
    # ---------------- Anniversary ----------------
    _p(
        category="first-anniversary",
        name="Paper Anniversary Keepsake Set",
        short_description="A letterpress map of the day you met, with a leather journal.",
        price=3899,
        compare_at_price=4499,
        occasion_tags="anniversary,wedding",
        recipient_tags="for-couples,for-her,for-him",
        theme_tags="keepsake,letterpress,journal,romance",
        is_customisable=True,
        allows_engraving=True,
        rating_average=4.9,
        rating_count=142,
        sold_count=380,
        inclusions=[
            {"name": "Letterpress star-map print, framed", "quantity": "1"},
            {"name": "Full-grain leather journal, embossed", "quantity": "1"},
            {"name": "Rose and oud candle", "quantity": "1"},
            {"name": "Chocolate truffles", "quantity": "12 pieces"},
        ],
    ),
    _p(
        category="milestone-years",
        name="Silver Jubilee Celebration Hamper",
        short_description="Silver-plated frame, aged balsamic and a bottle of sparkling.",
        price=8999,
        compare_at_price=10499,
        occasion_tags="anniversary,silver-jubilee,wedding",
        recipient_tags="for-parents,for-couples",
        theme_tags="luxe,silver,gourmet,milestone",
        is_luxe=True,
        allows_engraving=True,
        stock_quantity=12,
        rating_average=4.9,
        rating_count=68,
        sold_count=140,
        inclusions=[
            {"name": "Silver-plated photo frame, engraved", "quantity": "1"},
            {"name": "25-year aged balsamic", "quantity": "250ml"},
            {"name": "Sparkling grape pressing", "quantity": "750ml"},
            {"name": "Belgian praline assortment", "quantity": "24 pieces"},
        ],
    ),
    _p(
        category="wedding-gifting",
        name="Nikah and Shaadi Welcome Hamper",
        short_description="Guest welcome hamper for destination weddings. Bulk pricing.",
        price=1999,
        occasion_tags="wedding,anniversary",
        recipient_tags="corporate,for-friends",
        theme_tags="wedding,welcome,bulk,traditional",
        is_customisable=True,
        stock_quantity=300,
        sold_count=2800,
        rating_average=4.6,
        rating_count=94,
        inclusions=[
            {"name": "Printed welcome card with itinerary", "quantity": "1"},
            {"name": "Dry fruit and mithai selection", "quantity": "300g"},
            {"name": "Copper water bottle", "quantity": "1"},
            {"name": "Attar roll-on", "quantity": "6ml"},
        ],
    ),
    _p(
        category="work-anniversary",
        name="Years Of Service Recognition Box",
        short_description="Engraved crystal award with a gourmet pairing box.",
        price=4599,
        occasion_tags="work-anniversary,corporate,promotion",
        recipient_tags="corporate,for-him,for-her",
        theme_tags="corporate,award,engraved,gourmet",
        is_customisable=True,
        allows_engraving=True,
        stock_quantity=150,
        rating_average=4.5,
        rating_count=57,
        sold_count=460,
        inclusions=[
            {"name": "Engraved crystal award", "quantity": "1"},
            {"name": "Single-origin coffee", "quantity": "250g"},
            {"name": "Artisan chocolate selection", "quantity": "12 pieces"},
            {"name": "Leather cardholder", "quantity": "1"},
        ],
    ),
    _p(
        category="first-anniversary",
        name="One Year Together Petite Box",
        short_description="A compact anniversary box under two and a half thousand.",
        price=2299,
        compare_at_price=2699,
        occasion_tags="anniversary,valentines",
        recipient_tags="for-couples,for-her",
        theme_tags="romance,chocolate,candle,compact",
        same_day_delivery=True,
        is_new_arrival=True,
        rating_average=4.5,
        rating_count=73,
        sold_count=290,
        inclusions=[
            {"name": "Rose and oud candle", "quantity": "1"},
            {"name": "Heart-shaped truffles", "quantity": "9 pieces"},
            {"name": "Anniversary card", "quantity": "1"},
        ],
    ),
    # ---------------- Birthday ----------------
    _p(
        category="midnight-surprise",
        name="Midnight Birthday Surprise Hamper",
        short_description="Delivered between 11pm and midnight across eight metros.",
        description=(
            "Timed to land in the last hour of the day. A half-kilo truffle cake, "
            "helium-free balloon garland, a candle set and a hand-lettered banner, "
            "delivered between 11pm and 12am."
        ),
        price=2999,
        compare_at_price=3499,
        occasion_tags="birthday,midnight",
        recipient_tags="for-her,for-him,for-friends",
        theme_tags="cake,balloons,surprise,midnight",
        same_day_delivery=True,
        is_bestseller=True,
        rating_average=4.7,
        rating_count=612,
        sold_count=3400,
        inclusions=[
            {"name": "Belgian truffle cake", "quantity": "500g"},
            {"name": "Balloon garland kit", "quantity": "1"},
            {"name": "Numeral candle set", "quantity": "1"},
            {"name": "Hand-lettered banner", "quantity": "1"},
        ],
    ),
    _p(
        category="milestone-birthdays",
        name="Thirty And Thriving Hamper",
        short_description="A milestone box with engraved barware and single malt chocolate.",
        price=5499,
        compare_at_price=6299,
        occasion_tags="birthday,milestone",
        recipient_tags="for-him,for-her,for-friends",
        theme_tags="barware,engraved,milestone,chocolate",
        allows_engraving=True,
        is_customisable=True,
        rating_average=4.8,
        rating_count=121,
        sold_count=340,
        inclusions=[
            {"name": "Engraved crystal tumblers", "quantity": "2"},
            {"name": "Single malt infused chocolate", "quantity": "200g"},
            {"name": "Leather coaster set", "quantity": "4"},
            {"name": "Milestone card", "quantity": "1"},
        ],
    ),
    _p(
        category="for-kids",
        name="Little Explorer Birthday Hamper",
        short_description="A wooden puzzle, story book and no-sugar treats, ages 4 to 8.",
        price=1699,
        compare_at_price=1999,
        occasion_tags="birthday,childrens-day",
        recipient_tags="for-kids",
        theme_tags="toys,books,kids,educational",
        same_day_delivery=True,
        is_new_arrival=True,
        rating_average=4.6,
        rating_count=88,
        sold_count=410,
        inclusions=[
            {"name": "Wooden map puzzle", "quantity": "1"},
            {"name": "Illustrated story book", "quantity": "1"},
            {"name": "Fruit-sweetened treats", "quantity": "200g"},
            {"name": "Sticker sheet and crayons", "quantity": "1 set"},
        ],
    ),
    _p(
        category="birthday-luxe",
        name="LUXE Birthday Grand Hamper",
        short_description="Our largest birthday hamper. Champagne flutes, caviar, truffles.",
        price=12999,
        compare_at_price=14999,
        occasion_tags="birthday,milestone,anniversary",
        recipient_tags="for-her,for-him,for-couples",
        theme_tags="luxe,gourmet,crystal,premium",
        is_luxe=True,
        allows_engraving=True,
        stock_quantity=8,
        rating_average=5.0,
        rating_count=34,
        sold_count=72,
        inclusions=[
            {"name": "Crystal champagne flutes, engraved", "quantity": "2"},
            {"name": "Truffle-infused olive oil", "quantity": "250ml"},
            {"name": "Belgian couverture assortment", "quantity": "36 pieces"},
            {"name": "Saffron and pistachio nougat", "quantity": "300g"},
            {"name": "Oud and amber candle", "quantity": "1"},
        ],
    ),
    _p(
        category="midnight-surprise",
        name="Birthday Bloom and Cake Duo",
        short_description="Fresh lilies with a red velvet jar cake, same-day.",
        price=1899,
        occasion_tags="birthday,congratulations",
        recipient_tags="for-her,for-friends,for-parents",
        theme_tags="flowers,cake,fresh,same-day",
        same_day_delivery=True,
        is_bestseller=True,
        rating_average=4.5,
        rating_count=347,
        sold_count=2100,
        inclusions=[
            {"name": "Fresh oriental lilies", "quantity": "6 stems"},
            {"name": "Red velvet jar cakes", "quantity": "2"},
            {"name": "Birthday card", "quantity": "1"},
        ],
    ),
    _p(
        category="milestone-birthdays",
        name="Fifty Golden Years Hamper",
        short_description="A gold-accented milestone hamper with a personalised timeline.",
        price=7999,
        compare_at_price=8999,
        occasion_tags="birthday,milestone,anniversary",
        recipient_tags="for-parents,for-him,for-her",
        theme_tags="luxe,gold,milestone,keepsake",
        is_luxe=True,
        is_customisable=True,
        stock_quantity=15,
        rating_average=4.9,
        rating_count=52,
        sold_count=118,
        inclusions=[
            {"name": "Personalised life-timeline print, framed", "quantity": "1"},
            {"name": "Gold-rimmed teacups", "quantity": "2"},
            {"name": "Saffron and almond mithai", "quantity": "500g"},
            {"name": "Aged Assam tea", "quantity": "100g"},
        ],
    ),
]

REVIEW_SAMPLES: list[tuple[int, str, str]] = [
    (
        5,
        "Arrived exactly as pictured",
        "Packaging was genuinely beautiful, and it reached Pune a day early.",
    ),
    (
        5,
        "Worth every rupee",
        "Sent this to my sister and she called the moment she opened it.",
    ),
    (
        4,
        "Lovely, one item was small",
        "Everything was excellent, though the candle is smaller than I expected.",
    ),
    (
        5,
        "Repeat customer now",
        "Third hamper from Gyffty this year. The consistency keeps me coming back.",
    ),
    (
        4,
        "Great for corporate",
        "Ordered forty for our team. Finance was happy, the team was happier.",
    ),
]


# Launch coupon book. Marketing edits these through /api/v1/admin/coupons once
# the site is live; this is only the starting state.
COUPONS: list[dict] = [
    {
        "code": "GYFFTY10",
        "label": "10% off",
        "description": "10% off your first hamper, on orders above 1,999.",
        "discount_type": "percent",
        "value": 10,
        "min_order_value": 1999,
        "max_discount": 1500,
        "usage_limit_per_user": 1,
        "is_public": True,
    },
    {
        "code": "WELCOME300",
        "label": "300 off",
        "description": "Flat 300 off orders above 2,499.",
        "discount_type": "flat",
        "value": 300,
        "min_order_value": 2499,
        "is_public": True,
    },
    {
        "code": "LUXE15",
        "label": "15% off LUXE",
        "description": "15% off orders above 4,999.",
        "discount_type": "percent",
        "value": 15,
        "min_order_value": 4999,
        "max_discount": 3000,
        "is_public": True,
    },
    {
        "code": "CORPORATE20",
        "label": "20% off bulk orders",
        "description": "Negotiated rate for corporate accounts.",
        "discount_type": "percent",
        "value": 20,
        "min_order_value": 25000,
        "max_discount": 15000,
        "is_public": False,
    },
]
